# Generated by Django 5.0.6 on 2024-06-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orange_hrm_password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='orange_hrm_username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
